const escapeHtml = (value: string) => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

export function renderEmailLayout(paragraphs: string[], options: { action?: { label: string; url: string }; extraFooter?: string[]; signoff?: string; unsubscribeUrl?: string } = {}) {
  const p = (value: string) => `<p style="margin:0 0 20px;line-height:1.6">${escapeHtml(value).replace(/\n/g, "<br>")}</p>`;
  const action = options.action ? `<p style="margin:28px 0"><a href="${escapeHtml(options.action.url)}" style="display:inline-block;background:#0071e3;color:#ffffff;text-decoration:none;padding:12px 20px;border-radius:6px">${escapeHtml(options.action.label)}</a></p><p style="color:#62656c;font-size:13px">${escapeHtml(options.action.url)}</p>` : "";
  const extra = options.extraFooter?.map((line) => `<p style="margin:12px 0 0">${escapeHtml(line)}</p>`).join("") || "";
  return `<div style="background:#ffffff;color:#1d1d1f;font:16px/1.6 -apple-system,BlinkMacSystemFont,'Helvetica Neue',Arial,sans-serif;max-width:600px;margin:auto;padding:32px"><img src="https://loveleedaystudios.com/site/assets/mark-ink-512.png" width="28" height="28" alt="" style="display:inline-block;vertical-align:middle;width:28px;height:28px;object-fit:contain"><span style="vertical-align:middle;margin-left:10px;font-size:13px;letter-spacing:.2em;font-weight:600;color:#1d1d1f">LOVELEEDAY</span><div style="height:28px;line-height:28px">&nbsp;</div>${paragraphs.map(p).join("")}${action}${p(options.signoff || "Warmly,\nThe LOVELEEDAY team")}<div style="border-top:1px solid #e4e5e9;padding-top:20px;margin-top:32px;color:#62656c;font-size:13px">LOVELEEDAY Studios LLC · <a href="https://loveleedaystudios.com" style="color:#0066cc">loveleedaystudios.com</a>${extra}${options.unsubscribeUrl ? `<p style="margin:12px 0 0">If you would rather not hear from us again, <a href="${escapeHtml(options.unsubscribeUrl)}" style="color:#62656c">unsubscribe here</a>.</p>` : ""}</div></div>`;
}

export const emailDocument = (content: string) => `<!doctype html><meta charset="utf-8"><body style="margin:0;background:#f5f5f7;padding:24px">${content}</body>`;
