app = 'arthur-online'
primary_region = 'ord'

[build]
  vm_size = "performance-4x"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2048mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "arthur_data"
  destination = "/data"
