-- Public API v1 reads, webhook event queue and delivery, and an atomic token rotation.
-- Server RPCs are gated by private.server_ok_named(p_secret, 'connectors-server') like every other server RPC in 20261005_10.
-- Idempotent: safe to apply twice.

-- ── keyset paging columns (stable cursor; no row counting per call) ──────────────────────────────────
alter table public.tenant_connections add column if not exists seq bigint generated by default as identity;
alter table public.approvals add column if not exists seq bigint generated by default as identity;
create index if not exists tenant_connections_tenant_seq_idx on public.tenant_connections (tenant_id, seq);
create index if not exists approvals_tenant_seq_idx on public.approvals (tenant_id, seq);

-- ── webhook queue columns ────────────────────────────────────────────────────────────────────────────
alter table public.webhook_deliveries add column if not exists payload jsonb;
alter table public.webhook_deliveries add column if not exists next_at timestamptz not null default now();
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'webhook_deliveries_status_check') then
    alter table public.webhook_deliveries add constraint webhook_deliveries_status_check
      check (status = any (array['pending', 'retry', 'delivered', 'failed']));
  end if;
end $$;
create index if not exists webhook_deliveries_due_idx on public.webhook_deliveries (next_at) where status in ('pending', 'retry');

-- ── atomic token rotation ────────────────────────────────────────────────────────────────────────────
-- Writes only when the stored set's rotated_at still equals the one the refresh started from (null = nothing stored yet).
create or replace function public.connection_rotate_tokens(p_secret text, p_connection uuid, p_tokens jsonb, p_rotated_at timestamptz, p_expected_rotated_at timestamptz)
returns boolean language plpgsql security definer set search_path = '' as $$
declare v_tenant uuid; v_key text; v_set jsonb; v_cur timestamptz; v_exists boolean;
begin
  if not private.server_ok_named(p_secret, 'connectors-server') then raise exception 'server only'; end if;
  if p_rotated_at is null then raise exception 'rotated_at is required'; end if;
  if p_tokens is null or jsonb_typeof(p_tokens) <> 'object' or coalesce(p_tokens ->> 'access_token', '') = '' then raise exception 'access_token is required'; end if;
  select tenant_id into v_tenant from public.tenant_connections where id = p_connection;
  if v_tenant is null then raise exception 'unknown connection'; end if;
  v_key := private.tenant_key(v_tenant, true);
  -- lock the stored row so the compare and the write are one step
  select true, ((extensions.pgp_sym_decrypt(s.ciphertext, v_key)::jsonb) ->> 'rotated_at')::timestamptz into v_exists, v_cur
    from private.connection_secrets s where s.connection_id = p_connection for update;
  if v_cur is distinct from p_expected_rotated_at then return false; end if;
  if v_cur is not null and v_cur >= p_rotated_at then return false; end if;
  v_set := (p_tokens - 'rotated_at') || jsonb_build_object('rotated_at', p_rotated_at);
  if coalesce(v_exists, false) then
    update private.connection_secrets set ciphertext = extensions.pgp_sym_encrypt(v_set::text, v_key),
      fields = (select array_agg(k order by k) from jsonb_object_keys(v_set) k), created_at = now() where connection_id = p_connection;
  else
    insert into private.connection_secrets (connection_id, ciphertext, fields)
      values (p_connection, extensions.pgp_sym_encrypt(v_set::text, v_key), (select array_agg(k order by k) from jsonb_object_keys(v_set) k));
  end if;
  update public.tenant_connections set token_expires_at = nullif(p_tokens ->> 'expires_at', '')::timestamptz, error = null, updated_at = now()
    where id = p_connection;
  return true;
end $$;

-- ── public API reads (tenant comes from api_key_verify on the server; never from the caller) ─────────
create or replace function public.public_api_connections(p_secret text, p_tenant uuid, p_after bigint, p_limit integer)
returns table(seq bigint, id uuid, connector_key text, status text, health text, last_sync timestamptz, rows integer)
language plpgsql stable security definer set search_path = '' as $$
#variable_conflict use_column
begin
  if not private.server_ok_named(p_secret, 'connectors-server') then raise exception 'server only'; end if;
  return query select c.seq, c.id, coalesce(c.definition_key, c.connector_key), c.status, coalesce(c.health, 'unknown'), c.last_success_at, coalesce(c.last_rows, 0)
    from public.tenant_connections c where c.tenant_id = p_tenant and c.seq > coalesce(p_after, 0)
    order by c.seq limit least(greatest(coalesce(p_limit, 100), 1), 101);
end $$;

create or replace function public.public_api_records(p_secret text, p_tenant uuid, p_after bigint, p_limit integer, p_connection text, p_object text)
returns table(seq bigint, id uuid, connection_id uuid, source_system text, object text, source_ref text, payload jsonb, observed_at timestamptz, valid_from timestamptz)
language plpgsql stable security definer set search_path = '' as $$
#variable_conflict use_column
begin
  if not private.server_ok_named(p_secret, 'connectors-server') then raise exception 'server only'; end if;
  return query select r.seq, r.id, r.connection_id, r.source_system, r.object, r.source_ref, r.payload, r.observed_at, r.valid_from
    from public.ingested_records r where r.tenant_id = p_tenant and r.seq > coalesce(p_after, 0)
      and (p_connection is null or r.connection_id::text = p_connection) and (p_object is null or r.object = p_object)
    order by r.seq limit least(greatest(coalesce(p_limit, 100), 1), 101);
end $$;

create or replace function public.public_api_approvals(p_secret text, p_tenant uuid, p_after bigint, p_limit integer, p_status text)
returns table(seq bigint, id uuid, gate text, title text, detail text, status text, source_ref text, created_at timestamptz, decided_at timestamptz)
language plpgsql stable security definer set search_path = '' as $$
#variable_conflict use_column
begin
  if not private.server_ok_named(p_secret, 'connectors-server') then raise exception 'server only'; end if;
  return query select a.seq, a.id, a.gate, a.title, a.detail, a.status, a.source_ref, a.created_at, a.decided_at
    from public.approvals a where a.tenant_id = p_tenant and a.seq > coalesce(p_after, 0) and (p_status is null or a.status = p_status)
    order by a.seq limit least(greatest(coalesce(p_limit, 100), 1), 101);
end $$;

-- ── webhook events: queued in the SAME transaction as the change that caused them ───────────────────
create or replace function private.webhook_enqueue(p_tenant uuid, p_event text, p_data jsonb) returns void
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.webhook_deliveries (endpoint_id, tenant_id, event, status, attempt, payload, next_at)
  select e.id, p_tenant, p_event, 'pending', 1,
         jsonb_build_object('id', gen_random_uuid(), 'type', p_event, 'tenant', p_tenant, 'created_at', now(), 'data', p_data), now()
    from public.webhook_endpoints e where e.tenant_id = p_tenant and e.active and p_event = any (e.events);
end $$;
revoke all on function private.webhook_enqueue(uuid, text, jsonb) from public, anon, authenticated;

create or replace function private.tg_webhook_sync_runs() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if old.status = 'running' and new.status in ('succeeded', 'partial', 'failed') then
    perform private.webhook_enqueue(new.tenant_id, case when new.status = 'failed' then 'sync.failed' else 'sync.succeeded' end,
      jsonb_build_object('connection_id', new.connection_id, 'object', new.object, 'run_id', new.id, 'status', new.status,
                         'rows_read', new.rows_read, 'rows_written', new.rows_written, 'finished_at', new.finished_at));
    if new.status <> 'failed' and coalesce(new.rows_written, 0) > 0 then
      perform private.webhook_enqueue(new.tenant_id, 'record.ingested',
        jsonb_build_object('connection_id', new.connection_id, 'object', new.object, 'run_id', new.id, 'new_records', new.rows_written));
    end if;
  end if;
  return new;
end $$;
drop trigger if exists webhook_sync_runs on public.sync_runs;
create trigger webhook_sync_runs after update of status on public.sync_runs for each row execute function private.tg_webhook_sync_runs();

create or replace function private.tg_webhook_approvals() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    perform private.webhook_enqueue(new.tenant_id, 'approval.proposed', jsonb_build_object('approval_id', new.id, 'gate', new.gate, 'title', new.title, 'status', new.status));
  elsif old.status = 'pending' and new.status <> 'pending' then
    perform private.webhook_enqueue(new.tenant_id, 'approval.decided', jsonb_build_object('approval_id', new.id, 'gate', new.gate, 'title', new.title, 'status', new.status, 'decided_at', new.decided_at));
  end if;
  return new;
end $$;
drop trigger if exists webhook_approvals on public.approvals;
create trigger webhook_approvals after insert or update of status on public.approvals for each row execute function private.tg_webhook_approvals();

create or replace function private.tg_webhook_connection_health() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if new.health is distinct from old.health then
    perform private.webhook_enqueue(new.tenant_id, 'connection.health_changed',
      jsonb_build_object('connection_id', new.id, 'connector', coalesce(new.definition_key, new.connector_key), 'from', old.health, 'to', new.health));
  end if;
  return new;
end $$;
drop trigger if exists webhook_connection_health on public.tenant_connections;
create trigger webhook_connection_health after update of health on public.tenant_connections for each row execute function private.tg_webhook_connection_health();

-- ── delivery worker RPCs ─────────────────────────────────────────────────────────────────────────────
-- Leases due rows for 5 minutes so a second worker run skips them; the record call releases or finishes the row.
-- An endpoint whose signing secret cannot be decrypted (e.g. its tenant key was shredded) fails that delivery alone;
-- it never stops the rest of the batch.
create or replace function public.webhook_deliveries_due(p_secret text, p_limit integer)
returns table(id uuid, url text, secret text, payload jsonb, attempt integer)
language plpgsql security definer set search_path = '' as $$
#variable_conflict use_column
declare r record; v_secret text;
begin
  if not private.server_ok_named(p_secret, 'connectors-server') then raise exception 'server only'; end if;
  for r in
    select d.id, d.tenant_id, d.payload, d.attempt, e.url, e.secret_ct
      from public.webhook_deliveries d join public.webhook_endpoints e on e.id = d.endpoint_id and e.tenant_id = d.tenant_id
     where d.status in ('pending', 'retry') and d.next_at <= now() and e.active and d.payload is not null
     order by d.next_at, d.id limit least(greatest(coalesce(p_limit, 20), 1), 20)
     for update of d skip locked
  loop
    begin
      v_secret := extensions.pgp_sym_decrypt(r.secret_ct, private.tenant_key(r.tenant_id, false));
    exception when others then
      update public.webhook_deliveries set status = 'failed', at = now() where webhook_deliveries.id = r.id;
      continue;
    end;
    update public.webhook_deliveries set next_at = now() + interval '5 minutes' where webhook_deliveries.id = r.id;
    id := r.id; url := r.url; secret := v_secret; payload := r.payload; attempt := r.attempt;
    return next;
  end loop;
end $$;

create or replace function public.webhook_delivery_record(p_secret text, p_id uuid, p_status text, p_response_code integer, p_attempt integer, p_next_at timestamptz)
returns void language plpgsql security definer set search_path = '' as $$
begin
  if not private.server_ok_named(p_secret, 'connectors-server') then raise exception 'server only'; end if;
  if p_status is null or p_status not in ('delivered', 'retry', 'failed') then raise exception 'invalid delivery status'; end if;
  update public.webhook_deliveries set status = p_status, response_code = p_response_code,
    attempt = case when p_status = 'retry' then p_attempt + 1 else p_attempt end,
    next_at = case when p_status = 'retry' then coalesce(p_next_at, now() + interval '1 minute') else next_at end, at = now()
  where id = p_id and status in ('pending', 'retry') and attempt = p_attempt;
  if not found then raise exception 'delivery was already handled'; end if;
end $$;

revoke all on function public.connection_rotate_tokens(text, uuid, jsonb, timestamptz, timestamptz),
  public.public_api_connections(text, uuid, bigint, integer), public.public_api_records(text, uuid, bigint, integer, text, text),
  public.public_api_approvals(text, uuid, bigint, integer, text), public.webhook_deliveries_due(text, integer),
  public.webhook_delivery_record(text, uuid, text, integer, integer, timestamptz) from public;
grant execute on function public.connection_rotate_tokens(text, uuid, jsonb, timestamptz, timestamptz),
  public.public_api_connections(text, uuid, bigint, integer), public.public_api_records(text, uuid, bigint, integer, text, text),
  public.public_api_approvals(text, uuid, bigint, integer, text), public.webhook_deliveries_due(text, integer),
  public.webhook_delivery_record(text, uuid, text, integer, integer, timestamptz) to anon, authenticated, service_role;
