// GENERATED by scripts/gen-connector-ui-catalog.mjs from data/connectors/systems/*.json. Do not edit by hand.
export const ADMIN_STEPS: Record<string, { admin: string; wait: string }> = {
 "acumatica": {
  "admin": "Open Connected Applications (SM303010), add an OAuth 2.0 application (flow, redirect URI, scopes), generate shared secret; client ID format <GUID>@<CompanyID>; create/assign an API user with a role; confirm license allows web services API users.",
  "wait": "Same day after customer admin step"
 },
 "adp-workforce-now": {
  "admin": "Per ADP: client logs into API Central and generates a mutual SSL certificate; client authorizes the partner app/credentials for their ADP org via Marketplace subscription.",
  "wait": ""
 },
 "airtable": {
  "admin": "Airtable user authorizes the LOVELEEDAY integration and picks the workspaces and bases it may read.",
  "wait": "Immediate"
 },
 "amazon-s3": {
  "admin": "Create an IAM role in their account with the trust policy and read-only policy in customer_grant_statements, then send us the role ARN. We generate the ExternalId, unique per customer: per AWS 'The ExternalId value must be unique among Example Corp's customers and controlled by Example Corp, not its customers.'",
  "wait": ""
 },
 "appfolio": {
  "admin": "Partner integrations are enabled for a customer account by AppFolio/the customer through the Stack marketplace; exact steps not on pages read.",
  "wait": ""
 },
 "azure-synapse": {
  "admin": "A Microsoft Entra admin on the workspace creates a user for our Entra app in the target database and grants read, and opens the workspace firewall to our egress IPs. Note: Microsoft banner on the doc page states Fabric Data Warehouse is the new recommended path and dedicated pools can upgrade to Fabric.",
  "wait": ""
 },
 "blackbaud-raisers-edge-nxt": {
  "admin": "A Blackbaud user with rights authorizes our registered app through the OAuth authorization code flow for their Raiser's Edge NXT environment (environment/tenant selection happens at consent). Customer may also need to be entitled to the API under their RE NXT license.",
  "wait": ""
 },
 "bloomerang": {
  "admin": "",
  "wait": "Manual issuance of client credentials"
 },
 "box": {
  "admin": "Per Box docs: server-side apps (CCG, JWT) 'must be authorized' by the enterprise admin in Admin Console > Apps > Custom Apps Manager; OAuth 2.0 apps only need enablement 'when your enterprise leaves unpublished apps inactive by default'. Customer creates a service-account-scoped collaboration or grants app access.",
  "wait": ""
 },
 "brevo": {
  "admin": "Customer admin opens SMTP & API > API keys in Brevo, generates a v3 key, and pastes it into LOVELEEDAY (header 'api-key').",
  "wait": "Immediate"
 },
 "buildium": {
  "admin": "Per Propexo's Buildium guide (secondary, matches Buildium help): admin user on a Premium subscription turns on Settings > Application settings > System preferences > API settings > Open API toggle, then Settings > Developer Tools > Create API Key, names it, and copies the client ID and secret to us.",
  "wait": "Immediate once customer creates key"
 },
 "calendly": {
  "admin": "Calendly user authorizes the LOVELEEDAY app; access follows that user's account and organization role.",
  "wait": "Immediate for the Sandbox app;"
 },
 "cityworks": {
  "admin": "Expose the Cityworks web services (often behind VPN/firewall, on-prem or Trimble-hosted) to us and create a dedicated service user..",
  "wait": "Depends on customer IT"
 },
 "clickup": {
  "admin": "Workspace member authorizes the LOVELEEDAY app and picks the workspaces to share; access equals that user's permissions.",
  "wait": "Immediate"
 },
 "clio-manage": {
  "admin": "A user at the firm authorizes our app via the OAuth consent screen (in their region); firm admin approval may be required by firm policy.",
  "wait": "Immediate for unlisted apps"
 },
 "clover": {
  "admin": "Merchant owner installs our app from the Clover App Market (or private install link) and approves permissions; changing permissions later requires uninstall and reinstall.",
  "wait": ""
 },
 "csv-excel-upload": {
  "admin": "Export report to CSV or XLSX from their system and upload via portal.",
  "wait": ""
 },
 "databricks": {
  "admin": "Create a service principal, generate an OAuth secret, grant Unity Catalog privileges and CAN USE on a SQL warehouse, then send us workspace host, client ID and secret via our secure form. Alternative with no credentials: Delta Sharing.",
  "wait": ""
 },
 "docusign": {
  "admin": "Account admin or user consents to the integration key in the DocuSign consent screen; org admins may need to pre-authorize for JWT grant.",
  "wait": ""
 },
 "dropbox-business": {
  "admin": "Team admin authorizes the app; per Dropbox, scopes requested via the Business API yield a token 'associated with the team (rather than the administrator who authorized it)'. Use Dropbox-API-Select-User header to act as members.",
  "wait": ""
 },
 "dynamics-365-business-central": {
  "admin": "Entra admin consents to our multi-tenant app (admin consent URL); BC admin opens Microsoft Entra Applications page in the environment, adds our client ID, sets state Enabled and assigns permission sets (e.g. D365 READ / API-access sets).(S2S doc page found by search only).",
  "wait": "Same day after customer admin consent"
 },
 "dynamics-365-finance-operations": {
  "admin": "Entra admin registers/consents our app (multi-tenant); then in F&O: System administration > Setup > Microsoft Entra applications > New, enter Client Id, Name, and a service-account User ID with least-privilege security roles, Save. Needs data entities marked IsPublic.",
  "wait": "Same day after customer admin action"
 },
 "eclinicalworks": {
  "admin": "A practice administrator enables the LOVELEEDAY app for the practice, and a user authorizes it; PHI handling and a BAA are required before any live data.",
  "wait": "Sandbox immediate;"
 },
 "epicor-prophet-21": {
  "admin": "",
  "wait": ""
 },
 "esri-arcgis": {
  "admin": "In ArcGIS Online/Enterprise: register an app (OAuth client id/secret) or create an API key with item access, and share the target feature layers with it (or provide a read-only service account). Customer-hosted Enterprise servers must be reachable from us.",
  "wait": "Immediate"
 },
 "fleetio": {
  "admin": "The customer creates an API key and shares the account token from Fleetio Manage API Keys.",
  "wait": ""
 },
 "freshdesk": {
  "admin": "Customer opens Profile settings in Freshdesk, copies their API key, and pastes it with their Freshdesk domain (https://<domain>.freshdesk.com) into LOVELEEDAY. No OAuth app exists.",
  "wait": "Immediate"
 },
 "google-bigquery": {
  "admin": "Grant our service account dataset-level viewer plus a job-running role in a project that bills queries. Org policy may block external principals (domain-restricted sharing); admin must allow our domain/principal.",
  "wait": ""
 },
 "google-workspace": {
  "admin": "Workspace admin allowlists our OAuth client ID in Admin console > Security > API controls > App access control, or for domain-wide delegation authorizes our service account client ID and scopes..",
  "wait": ""
 },
 "gusto": {
  "admin": "Company admin approves the OAuth consent for the app",
  "wait": ""
 },
 "help-scout": {
  "admin": "Help Scout user (account admin recommended) accepts the LOVELEEDAY app.",
  "wait": "Immediate"
 },
 "homebase": {
  "admin": "",
  "wait": ""
 },
 "hubspot": {
  "admin": "Super Admin installs the app from our install link and approves scopes. Alternative: customer creates a Private App / service key with read scopes and shares the token.",
  "wait": "Immediate for unlisted OAuth app;"
 },
 "infor-cloudsuite": {
  "admin": "In Infor OS: API Gateway > Authorized Apps > + > type Backend Service, save, Download Credentials with Create Service Account enabled and a user chosen, then send us the.ionapi file securely. The product (M3, LN, CloudSuite Industrial/SyteLine, etc.) must be exposed through ION API and the service-account user needs security roles.",
  "wait": "Days, customer admin driven"
 },
 "intercom": {
  "admin": "Workspace admin authorizes the LOVELEEDAY app from our OAuth link and accepts the read-only permissions.",
  "wait": "Immediate"
 },
 "jira": {
  "admin": "Jira site admin or user consents to the LOVELEEDAY app and selects the Atlassian site; access equals that user's permissions.",
  "wait": "Immediate for a private app;"
 },
 "jobber": {
  "admin": "A Jobber account owner authorizes the LOVELEEDAY app.",
  "wait": "Immediate for a draft app;"
 },
 "laserfiche": {
  "admin": "Cloud admin creates a Service Principal user (Laserfiche doc: authenticates with a rotatable API key, no MFA), registers a service app in the Developer Console with that principal as service account, creates an access key, and grants the principal read rights on the target repository folders.",
  "wait": "Immediate once admin creates principal and key"
 },
 "mailchimp": {
  "admin": "Customer logs in at login.mailchimp.com authorize URL and approves; we call login.mailchimp.com/oauth2/metadata to obtain the dc (data center) for their API host. Alternative: customer generates an API key in Account > Extras > API keys and shares it.",
  "wait": "Immediate"
 },
 "mews": {
  "admin": "The property creates an AccessToken for the integration in its Mews account.",
  "wait": ""
 },
 "microsoft-365": {
  "admin": "Tenant Global Admin (or Privileged Role Admin) grants admin consent to our multi-tenant app via the admin-consent URL for the application permissions above; for SharePoint minimal access, admin grants Sites.Selected then grants our app per-site permission via POST /sites/{id}/permissions.",
  "wait": ""
 },
 "monday": {
  "admin": "Account member (admin if workspace policy restricts apps) installs the LOVELEEDAY app and accepts the read scopes.",
  "wait": "Immediate for the draft app;"
 },
 "mri-software": {
  "admin": "Provide their own MRI installation credentials (per Apideck: consumers provide only their own MRI installation credentials) and, if sponsoring, introduce us to MRI.(MRI portal gated).",
  "wait": "Per Apideck (secondary): 5-7 business days from application to intro call, then NDA, agreement, provisioning"
 },
 "netsuite": {
  "admin": "Admin (or user with Integration Application permission) goes to Setup > Integration > Manage Integrations > New, sets State Enabled, ticks Authorization Code Grant (https redirect URI) and/or Client Credentials (M2M), ticks REST Web Services scope, saves, and copies client ID and secret (shown only once).",
  "wait": "Same day if customer admin cooperates; no vendor approval"
 },
 "notion": {
  "admin": "A workspace member authorizes the LOVELEEDAY public integration and picks the pages and databases to share with it.",
  "wait": "Immediate for an unlisted public integration"
 },
 "oracle-fusion-cloud-erp": {
  "admin": "Create an integration user with a role that carries the needed Financials REST privileges (e.g. Accounts Receivable/Payables inquiry duties) and, for OAuth, register a confidential application in the Fusion IAM identity domain with grant types and scopes, then send us client ID/secret, pod URL.",
  "wait": "Days to weeks driven by customer IT/security; no vendor approval"
 },
 "pandadoc": {
  "admin": "The customer generates an API key in Settings > API and Integrations, or authorizes OAuth once a paid developer plan exists.",
  "wait": "Immediate for the sandbox"
 },
 "pipedrive": {
  "admin": "Pipedrive user with access installs the LOVELEEDAY app and accepts the scopes; admin may be needed for company-wide data.",
  "wait": ""
 },
 "procore": {
  "admin": "Company admin installs the app (custom or Marketplace) in their Procore company and, for DMSA, creates the service account and grants project permissions..",
  "wait": ""
 },
 "qad-adaptive-erp": {
  "admin": "QAD docs show QXtend must be installed and linked to the ERP databases (QXtend 1.10 required for Adaptive ERP 2022.1); customer would need QXtend Inbound/Outbound configured, and a service user. Alternatively the customer produces scheduled report/export files.",
  "wait": ""
 },
 "quickbooks-online": {
  "admin": "Company admin clicks Connect to QuickBooks and approves the consent screen selecting the company; no other setup.",
  "wait": ""
 },
 "sage-intacct": {
  "admin": "Create a Web Services user (Company > Admin > Web Services Users > Add) with a role of needed permissions; then Company > Setup > Company > Edit > Security > Authorized Client Applications > Add, enter our Client ID and the Web Services user ID. For legacy XML also authorize our Web Services sender ID. Customer's subscription must include Web Services.",
  "wait": ""
 },
 "salesforce": {
  "admin": "Org admin installs our External Client App / authorizes it (or approves the OAuth app), assigns permission set, and the user logs in and allows. API access requires Enterprise, Unlimited, Performance, Developer edition, or Professional with API add-on.",
  "wait": "Immediate for private use;"
 },
 "sap-business-one": {
  "admin": "Provide an externally reachable Service Layer URL (port 50000 or reverse proxy / VPN / IP allow-list), the CompanyDB name, and a dedicated B1 user with a license (e.g. Indirect Access/Professional) and read authorizations. Hosted customers: ask hosting partner to expose Service Layer.",
  "wait": "Days, driven by customer IT/network"
 },
 "sftp-drop": {
  "admin": "Customer sends an SSH public key and nightly-export job pushes CSV to the drop host using our supplied host key fingerprint.",
  "wait": ""
 },
 "shippo": {
  "admin": "The customer creates an API token in Shippo Settings > API and pastes it in.",
  "wait": "Immediate"
 },
 "shopify": {
  "admin": "Option A (custom per-store app): store admin creates a custom app in Settings > Apps > Develop apps, selects read scopes, installs, and gives us the Admin API token. Option B (public/unlisted distribution): merchant clicks install link and approves scopes.",
  "wait": ""
 },
 "snowflake": {
  "admin": "Option A (preferred for zero-credential): create a secure share and add our account. Option B: create a SERVICE user with our public key and a read-only role (statements below). Admin needs USERADMIN/SECURITYADMIN (CREATE USER requires USERADMIN or higher) and ACCOUNTADMIN for shares.",
  "wait": ""
 },
 "square": {
  "admin": "Square account owner clicks our Connect with Square link, reviews the permission list and clicks Allow; we receive the code and exchange it server-side.",
  "wait": "Immediate for OAuth; none"
 },
 "stripe": {
  "admin": "Customer admin clicks Connect with Stripe, signs in, selects the account and approves read_only access. Alternative with no Connect: customer creates a restricted API key (read-only on Charges, Customers, Invoices, Subscriptions, Balance transactions, Payouts) and pastes it.",
  "wait": "Immediate for OAuth read_only; Connect profile may require Stripe review"
 },
 "toast": {
  "admin": "Restaurant admin grants API access to the specific integration partner in Toast Web (partner access is per restaurant). Customer then supplies restaurant GUID / external ID. Fallback with no partner status: customer enables Toast Data Export nightly SFTP to our host (Toast Web > Integrations / data export).",
  "wait": ""
 },
 "trello": {
  "admin": "A Trello member authorizes the LOVELEEDAY app and grants the read scopes.",
  "wait": "Immediate"
 },
 "tyler-munis": {
  "admin": "Customer (the municipality) must have an active Tyler license and engage Tyler professional services to provision API credentials for us..",
  "wait": ""
 },
 "typeform": {
  "admin": "Typeform account member authorizes the LOVELEEDAY app and grants the read scopes.",
  "wait": "Immediate"
 },
 "workday": {
  "admin": "Per doc.workday.com search result: customer admin runs the 'Register API Client' task (Set Up: Tenant Setup - Security / Security Administration domains), supplying a unique client name and an x509 certificate public key plus the ISU user; creates an Integration System User and assigns it to a security group with view access to the needed domains and activates security policy changes.",
  "wait": ""
 },
 "wrike": {
  "admin": "A Wrike user authorizes the LOVELEEDAY app; access follows that user's account.",
  "wait": "Immediate"
 },
 "xero": {
  "admin": "User with Standard or Advisor role clicks Connect and authorizes the organisation(s) in Xero consent screen; connection list via /connections.",
  "wait": ""
 },
 "yardi-voyager": {
  "admin": "Customer must authorize the vendor with Yardi and request the interface be enabled on their Voyager database; Yardi then issues the web-services URL, interface credentials and license.(vendor page blocked).",
  "wait": ""
 },
 "zendesk": {
  "admin": "Zendesk admin authorizes the LOVELEEDAY OAuth client; each customer subdomain is entered at connect time.",
  "wait": "Immediate"
 },
 "zoho-crm": {
  "admin": "Zoho CRM user authorizes the scopes requested at connect time (scopes are chosen per authorization request, not on the client).",
  "wait": "Immediate"
 }
};
