import {lookup} from 'node:dns/promises';
import {isIP} from 'node:net';

const STEEL_URL=(process.env.ARTHUR_BROWSER_URL||'https://api.steel.dev').replace(/\/$/,'');
const STEEL_KEY=process.env.ARTHUR_BROWSER_SECRET||process.env.STEEL_API_KEY||'';
const headers=()=>({'content-type':'application/json',authorization:`Bearer ${STEEL_KEY}`});

function privateIp(ip:string){if(ip==='::1'||ip==='::'||/^(fc|fd|fe80):/i.test(ip))return true;if(isIP(ip)!==4)return false;const p=ip.split('.').map(Number);return p[0]===0||p[0]===10||p[0]===127||p[0]===169&&p[1]===254||p[0]===172&&p[1]>=16&&p[1]<=31||p[0]===192&&p[1]===168}
export async function safeBrowserUrl(raw:string){const u=new URL(raw);if(!['http:','https:'].includes(u.protocol))throw Error('http_url_required');const rows=await lookup(u.hostname,{all:true});if(!rows.length||rows.some(x=>privateIp(x.address)))throw Error('private_browser_target_blocked');return u.toString()}
async function steel(path:string,init:RequestInit={}){if(!STEEL_KEY)throw Error('arthur_browser_not_configured');const r=await fetch(`${STEEL_URL}${path}`,{...init,headers:{...headers(),...(init.headers||{})},signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error(`steel_${r.status}:${(await r.text()).slice(0,200)}`);return r}
export async function createBrowserSession(){const r=await steel('/v1/sessions',{method:'POST',body:JSON.stringify({stealthConfig:{},sessionContext:{id:'arthur-chat-browser'}})}),x=await r.json() as any;return String(x.id||x.session_id)}
async function withPage<T>(sessionId:string,fn:(page:any)=>Promise<T>){const {chromium}=await import('playwright');const ws=`wss://connect.steel.dev?apiKey=${encodeURIComponent(STEEL_KEY)}&sessionId=${encodeURIComponent(sessionId)}`,browser=await chromium.connectOverCDP(ws,{timeout:30000});try{const context=browser.contexts()[0]||await browser.newContext(),page=context.pages()[0]||await context.newPage();return await fn(page)}finally{await browser.close()}}
export type BrowserCommand={session_id?:string;action:'open'|'navigate'|'click'|'type'|'read'|'back'|'forward'|'refresh';url?:string;selector?:string;text?:string};
export async function operateBrowser(command:BrowserCommand){const sessionId=command.session_id||await createBrowserSession();return withPage(sessionId,async page=>{if(command.action==='open'||command.action==='navigate'){if(!command.url)throw Error('url_required');await page.goto(await safeBrowserUrl(command.url),{waitUntil:'domcontentloaded',timeout:30000})}else if(command.action==='click'){if(!command.selector)throw Error('selector_required');await page.locator(command.selector).first().click({timeout:10000})}else if(command.action==='type'){if(!command.selector)throw Error('selector_required');await page.locator(command.selector).first().fill(String(command.text||''),{timeout:10000})}else if(command.action==='back')await page.goBack({waitUntil:'domcontentloaded'});else if(command.action==='forward')await page.goForward({waitUntil:'domcontentloaded'});else if(command.action==='refresh')await page.reload({waitUntil:'domcontentloaded'});const [title,text]=await Promise.all([page.title(),page.locator('body').innerText().catch(()=> '')]);return{ok:true,session_id:sessionId,url:page.url(),title,text:text.slice(0,12000),screenshot_url:`/api/browser?session_id=${encodeURIComponent(sessionId)}&t=${Date.now()}`}})}
export async function browserScreenshot(sessionId:string):Promise<Buffer>{return await withPage<Buffer>(sessionId,page=>page.screenshot({type:'jpeg',quality:75}) as Promise<Buffer>)}
