// Executive brief. Written from templates: every number is injected from the computed result, never generated by a
// model. A sentence is only emitted when the figure behind it exists and has source rows.
import type { SnapshotResult } from './run.ts';

export interface Brief {
  headline: string;
  paragraphs: string[];
  figures: { label: string; value: string; rule: string | null; rows: number }[];
  generated_by: 'template';
}

const usd = (n: number) => '$' + n.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 });
const num = (n: number) => n.toLocaleString('en-US');
const plural = (n: number, one: string, many: string) => (n === 1 ? one : many);

export function buildBrief(r: SnapshotResult): Brief {
  const figures: Brief['figures'] = [];
  const paras: string[] = [];
  const flagged = r.findings.filter((f) => f.count > 0);
  const total = flagged.reduce((a, f) => a + f.count, 0);

  const sample = r.source === 'sample' ? 'This is a synthetic sample, not real company data. ' : '';
  paras.push(`${sample}We read ${num(r.rows_used)} price records as of ${r.as_of} and ran ${r.findings.length} of ${r.findings.length + r.skipped.length} checks. The integrity score is ${r.score.score} out of 100.`);
  figures.push({ label: 'Integrity score', value: `${r.score.score} / 100`, rule: null, rows: r.rows_used });

  const loss = r.findings.filter((f) => f.exposure.kind === 'loss' && f.exposure.amount !== null && f.exposure.amount > 0);
  if (loss.length) {
    const sum = loss.reduce((a, f) => a + (f.exposure.amount ?? 0), 0);
    const parts = loss.map((f) => `${usd(f.exposure.amount ?? 0)} from ${f.title.toLowerCase()}`);
    paras.push(loss.length === 1
      ? `Traced to specific rows, ${usd(sum)} of margin loss was found under "${loss[0].title.toLowerCase()}". The figure comes with its formula and the rows behind it.`
      : `Traced to specific rows, ${usd(sum)} of margin loss was found: ${parts.join('; ')}. Each figure comes with its formula and the rows behind it.`);
    for (const f of loss) figures.push({ label: `Loss: ${f.title}`, value: usd(f.exposure.amount ?? 0), rule: f.rule, rows: f.rows_total });
  }
  const expo = r.findings.filter((f) => f.exposure.kind === 'exposure' && f.count > 0);
  for (const f of expo) {
    paras.push(`${num(f.count)} ${f.unit} fall under "${f.title.toLowerCase()}". The file has no sales volume, so the dollar effect is exposure per unit, not a loss, and no total is claimed.`);
    figures.push({ label: `Exposure (per unit only): ${f.title}`, value: `${num(f.count)} ${f.unit}`, rule: f.rule, rows: f.rows_total });
  }
  const others = flagged.filter((f) => f.exposure.kind === 'none');
  if (others.length) {
    paras.push(`Other findings are counted but not priced, because the file holds no dollar basis for them. ${others.map((f) => `${f.title}: ${num(f.count)} ${f.unit}`).join('; ')}.`);
    for (const f of others) figures.push({ label: f.title, value: `${num(f.count)} ${f.unit}`, rule: f.rule, rows: f.rows_total });
  }
  if (!flagged.length) paras.push('None of the checks that could run flagged a record.');

  if (r.skipped.length) {
    paras.push(`${num(r.skipped.length)} ${plural(r.skipped.length, 'check', 'checks')} could not run on this file: ${r.skipped.map((s) => `${s.rule.replace(/_/g, ' ')} (${s.reason})`).join('; ')}.`);
  }
  paras.push(`Coverage is ${r.coverage.score} percent: ${r.coverage.basis}.`);
  figures.push({ label: 'Coverage', value: `${r.coverage.score}%`, rule: null, rows: r.rows_used });

  const headline = loss.length
    ? `${usd(loss.reduce((a, f) => a + (f.exposure.amount ?? 0), 0))} of margin loss found across ${num(total)} flagged ${plural(total, 'item', 'items')}`
    : total
      ? `${num(total)} flagged ${plural(total, 'item', 'items')} across ${flagged.length} ${plural(flagged.length, 'check', 'checks')}`
      : 'No flagged records on the checks that could run';
  return { headline, paragraphs: paras, figures, generated_by: 'template' };
}
