import { NextRequest, NextResponse } from "next/server";
import { getSupabaseAdmin } from "@/lib/supabase/admin";
import { authGate } from "@/lib/_auth";
import { companies } from "@/app/_data/compliance";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const RECORD = ["bank_statement", "tax_return", "financial_statement", "payroll", "annual_report", "banking"];
const RENEWABLE = ["license", "permit", "insurance", "lease"];
const GOAL_TITLE = "Compliance — Document Renewals";

type Doc = { id: string; entity: string | null; category: string | null; title: string | null; file_name: string; expires_at: string | null; is_archived: boolean; renewal_snoozed_until: string | null };

export async function GET(req: NextRequest) {
  const deny = authGate(req); if (deny) return deny;
  const db = getSupabaseAdmin();
  const today = new Date().toISOString().slice(0, 10);

  // 1. Clear misleading expiry on historical records (period-end ≠ renewal deadline)
  const { data: cleared } = await db.from("legal_documents")
    .update({ expires_at: null }).in("category", RECORD).not("expires_at", "is", null).select("id");

  // 2. Load ALL docs (incl. archived, so renewal tasks persist across re-runs)
  const { data: rows } = await db.from("legal_documents")
    .select("id,entity,category,title,file_name,expires_at,is_archived,renewal_snoozed_until");
  const docs = (rows ?? []) as Doc[];

  const tasks: { title: string; description: string }[] = [];
  let archived = 0;

  // 3. Expired renewable forms → archive; if no current replacement → renewal task
  for (const d of docs.filter(x => RENEWABLE.includes(x.category ?? "") && x.expires_at && x.expires_at < today)) {
    if (!d.is_archived) { await db.from("legal_documents").update({ is_archived: true }).eq("id", d.id); archived++; }
    const replacement = docs.find(x => x.id !== d.id && x.entity === d.entity && x.category === d.category
      && !x.is_archived && (!x.expires_at || x.expires_at >= today));
    if (!replacement) {
      tasks.push({ title: `Renew ${d.title || d.file_name} (${d.entity})`,
        description: `Expired ${d.expires_at}. No current replacement on file. Obtain + upload the renewed ${d.category}.` });
    }
  }

  // 3.5 Pre-expiry tiered renewal alerts (90/60/30/7-day; liquor license 120-day lead; honors snooze)
  const daysBetween = (a: string) => Math.ceil((new Date(a).getTime() - new Date(today).getTime()) / 86400000);
  let alerts = 0;
  for (const d of docs.filter(x => RENEWABLE.includes(x.category ?? "") && x.expires_at && x.expires_at >= today && !x.is_archived)) {
    if (d.renewal_snoozed_until && d.renewal_snoozed_until >= today) continue;
    const isLiquor = d.category === "license" && /liquor|mlcc|class c/i.test(`${d.title ?? ""} ${d.file_name}`);
    const lead = isLiquor ? 120 : 90;
    const out = daysBetween(d.expires_at!);
    if (out > lead) continue;
    const tier = out <= 7 ? "🔴 7-day" : out <= 30 ? "🟠 30-day" : out <= 60 ? "🟡 60-day" : isLiquor ? "120-day (liquor)" : "90-day";
    tasks.push({
      title: `Renew ${d.title || d.file_name} (${d.entity}) — due ${d.expires_at}`,
      description: `${tier} alert: expires in ${out} day(s) on ${d.expires_at}. Obtain + upload the renewed ${d.category}.${isLiquor ? " MLCC processing is slow — start now." : ""}`,
    });
    alerts++;
  }

  // 4. Missing required checklist items → obtain task
  const current = docs.filter(d => !d.is_archived);
  for (const co of companies) {
    const entRows = current.filter(d => d.entity === co.entity);
    const claimed = new Set<string>();
    for (const s of co.sections) for (const item of s.items) {
      if (!item.required) continue;
      const hit = entRows.find(r => r.category === item.category && !claimed.has(r.id) &&
        (!item.matchKeywords?.length || item.matchKeywords.some(k =>
          `${r.title ?? ""} ${r.file_name}`.toLowerCase().includes(k.toLowerCase()))));
      if (hit) { claimed.add(hit.id); }
      else tasks.push({ title: `Obtain ${item.label} (${co.name})`, description: item.note || `Required ${item.category} not on file.` });
    }
  }

  // 5. Upsert Compliance goal + insert non-duplicate task steps
  let goalId: string | null = null;
  const { data: g } = await db.from("arthur_goals").select("id").eq("title", GOAL_TITLE).neq("status", "archived").maybeSingle();
  if (g) goalId = g.id;
  else {
    const { data: ng } = await db.from("arthur_goals").insert({
      title: GOAL_TITLE, description: "Auto-generated by the compliance sweep — expired/missing documents for Arthur to renew or obtain.",
      status: "approved", priority: 1, arthur_can_execute: true, tags: ["compliance", "documents"],
    }).select("id").single();
    goalId = ng?.id ?? null;
  }
  let created = 0;
  if (goalId) {
    const { data: existing } = await db.from("arthur_goal_steps").select("title,status").eq("goal_id", goalId);
    const openTitles = new Set((existing ?? []).filter((s: { status: string }) => s.status !== "done").map((s: { title: string }) => s.title));
    let seq = (existing ?? []).length;
    for (const t of tasks) {
      if (openTitles.has(t.title)) continue;
      await db.from("arthur_goal_steps").insert({ goal_id: goalId, seq: seq++, title: t.title, description: t.description, status: "pending", arthur_action: "Obtain or renew this document and upload it to the legal vault." });
      created++;
    }
  }

  return NextResponse.json({
    ok: true, ran_at: new Date().toISOString(),
    records_expiry_cleared: cleared?.length ?? 0, forms_archived: archived, expiry_alerts: alerts,
    tasks_identified: tasks.length, tasks_created: created, goal: GOAL_TITLE,
  });
}
